server:
  port: 3002

eureka:
  instance:
    hostname: esb
    prefer-ip-address: true
  client:
    fetch-registry: false
    service-url:
      defaultZone:
        http://esa:3001/eureka,
        http://esc:3003/eureka
    register-with-eureka: false
spring:
  application:
    name: server_b