spring:
  application:
    name: mq-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: asakumo
    password: lemon
    virtual-host: /asakumo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bz1746578697
    url: jdbc:mysql://localhost:3306/current_services_ds?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone:
        http://esa:3001/eureka
        ,http://esb:3002/eureka,http://esc:3003/eureka
  instance:
    instance-id: mq-consumer-${server.port}
#    prefer-ip-address: true
