server:
  port: 3001

eureka:
  instance:
    hostname: esa
    prefer-ip-address: true
  client:
    fetch-registry: false
    service-url:
      defaultZone:
        http://esb:3002/eureka,
        http://esc:3003/eureka
    register-with-eureka: false
spring:
  application:
    name: server_a